elk:
  image: sebp/elk
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
     - elk-data:/var/lib/elasticsearch
proxy:
  links:
    - elk
  ports:
    - "80:80"
    - "443:443"
  image: nginx
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
