- name: install packages
  package:
    name: "{{ item }}"
  with_items:
    - docker
    - epel-release
    - python-pip
  become: yes
- name: install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - docker-compose  
  become: yes
- name: enable docker
  systemd:
    name: docker
    enabled: yes
    state: started
  become: yes
- name: copy docker compose files
  copy:
    src: files/docker-compose.yml
    dest: /root/docker-compose.yml
  become: yes
- name: copy nginx config
  copy:
    src: files/nginx
    dest: /root/
    setype: svirt_sandbox_file_t
  become: yes
- name: configure kernal parameters for docker
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: yes
  become: yes
- name: Create containers for elk and nginx
  shell: cd /root/ ; docker-compose up -d
  become: yes
