- name: install packages
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip 
    - python-dev 
    - jq 
    - git
    - python-software-properties
    - npm
  become: yes
- name: Install fluentd
  shell: curl -L https://toolbelt.treasuredata.com/sh/install-ubuntu-trusty-td-agent2.sh | sh
  args:
    creates: .installed_fluentd
  become: yes
- name: Install fluent plugins
  shell: "{{ item }}"
  with_items:
    - '/opt/td-agent/usr/sbin/td-agent-gem install fluent-plugin-elasticsearch'
    - '/opt/td-agent/usr/sbin/td-agent-gem install fluent-plugin-add'
    - '/opt/td-agent/usr/sbin/td-agent-gem install fluent-plugin-filter_typecast'
  become: yes
- name: Setup fluentd config
  template:
    src: templates/td-agent.j2
    dest: /etc/td-agent/td-agent.conf
  become: yes
- name: Enable fluentd
  service:
    name: td-agent
    state: restarted
    enabled: yes
  become: yes
- name: Setup directories
  file:
    path: "{{ item }}"
    state: directory
    owner: ubuntu
    group: ubuntu
  with_items:
    - /opt/results
    - /opt/logs
  become: yes
- name: checkout perfkit
  git:
    repo: 'https://github.com/GoogleCloudPlatform/PerfKitBenchmarker.git'
    dest: /opt/PerfKitBenchmarker
    force: yes
  become: yes
- name: Update perfkit permissions
  file:
    path: /opt/PerfKitBenchmarker
    owner: ubuntu
    group: ubuntu
    recurse: yes
  become: true
- name: Upgrade pip
  pip:
    name: pip
    state: latest
  become: true
- name: patch openstack requirements until our pull request is accepeted https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/1467
  lineinfile:
    path: /opt/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/requirements.txt
    regexp: "{{ item.old }}"
    line: "{{ item.new }}"
    backup: yes
  with_items:
    - { old: 'openstacksdk==0.9.10', new: 'openstacksdk>=0.9.10' }
    - { old: 'python-openstackclient==3.6.0', new: 'python-openstackclient>=3.6.0' }
- name: Install requirements via pip
  pip:
    requirements: "{{ item }}"
    state: latest
    chdir: /opt/PerfKitBenchmarker
  with_items:
    - requirements.txt
    - perfkitbenchmarker/providers/openstack/requirements.txt
    - perfkitbenchmarker/providers/aws/requirements.txt
  become: true
- name: Installing missing dep
  pip:
    name: babel
    state: present
    version: 2.3.4
  become: true
- name: Install Azure client
  shell: npm install azure-cli@0.10.4 -g 
  become: yes
- name: create nodejs symlink for Azure
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
